### ISSUE TITLE
Setup Vulkan SDK action not working as of today

### ISSUE THREAD

**Issue by wheremyfoodat** [humbletim/setup-vulkan-sdk#17]
Hello, I've been using this action in my repository and it seems to have started failing, making all builds and PRs fail.
I have tried deleting the Github Actions cache and rerunning the jobs but they're still failing.

All our workflows use the action like this:
```yaml
    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: latest
        vulkan-use-cache: true
        vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
   ```
   
 Our relevant Github workflows can be found here: https://github.com/wheremyfoodat/Panda3DS/tree/master/.github/workflows
 I've also attached the log generated by the vulkan setup action here:
[setup_vulkan_log.txt](https://github.com/humbletim/setup-vulkan-sdk/files/13126660/setup_vulkan_log.txt)

If you'd prefer to see the full CI log for this particular run then you can find it here: https://github.com/wheremyfoodat/Panda3DS/actions/runs/6631468473/job/18015376439?pr=328
