### ISSUE TITLE
Cache breaking builds?

### ISSUE THREAD

**Issue by rpavlik** [humbletim/setup-vulkan-sdk#28]
I'm getting a 'deprecated actions/cache@v2' error in a workflow where I'm not directly using it, but I am using this action. This is the only action I use exclusively in this one failing build, so I'm assuming it must be some transitive use thing. I can't find the transitive use, but wanted to at least log an issue in case somebody else saw this  and/or knew better what was going on.

```yaml
      - name: Prepare Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.290.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
```

https://github.com/KhronosGroup/OpenXR-SDK-Source/actions/runs/13682354519/job/38257588328#step:1:28

```
Current runner version: '2.322.0'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:11bd71901bbe5b1630ceea73d27597364c9af683)
Download action repository 'lukka/get-cmake@v3.31.6' (SHA:56d043d188c3612951d8755da8f4b709ec951ad6)
Download action repository 'humbletim/setup-vulkan-sdk@v1.2.0' (SHA:72eed4b9dbeac5de168f83da8e30b1d0f8ac7f14)
Getting action download info
Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
```
