### ISSUE TITLE
Support for installing glslang

### ISSUE THREAD

**Issue by jamestmartin** [humbletim/setup-vulkan-sdk#6]
I use the GLSL-to-SPIR-V compiler `glslangValidator` from [KhronosGroup/glslang](https://github.com/KhronosGroup/glslang) as part of my build process. I would greatly appreciate it if you'd consider adding an option to install it with this action.

**Comment by styler00dollar** [comment]
Any update?

**Comment by humbletim** [comment]
As of v1.2.0-beta this action now supports building and installing `glslangValidator` as well:

```yaml
 -name: Prepare Vulkan SDK
   uses: humbletim/setup-vulkan-sdk@v1.2.0-beta
   with:
     vulkan-query-version: 1.3.204.0
     vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang
     vulkan-use-cache: true
```

This action is mainly meant for compiling Vulkan SDK components from corresponding source code and with caching enabled it seems reasonable enough to include glslangValidator that way.

However, for projects that depend on multiple binary tools from the full Vulkan SDK, it may make more sense to just perform unattended installation of the official Vulkan SDK prebuilt release. In case useful to others I've put together a new action which automates that whole process for linux/mac/windows here: [actions/install-vulkan-sdk](https://github.com/marketplace/actions/install-vulkan-sdk).
